version: '3'

env:
  VERSION: 0.6.0-alpha
  NAME: wacomswitcher

tasks:
  build-flatpak:
    cmds:
      - flatpak-builder --force-clean --user --install-deps-from=flathub --repo=repo --install build.flatpak config/io.github.irishpatrick.WacomDisplaySwitcher.yml
    silent: true

  publish-flatpak:
    cmds:
      - flatpak build-bundle repo WacomDisplaySwitcher.flatpak io.github.irishpatrick.WacomDisplaySwitcher --runtime=repo --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo
    silent: true

  release:
    cmds:
      - docker build . -t wacom-display-switcher-build
      - id=$(docker create wacom-display-switcher-build) ; docker cp $id:/release.tar ./release.tar ; docker rm $id
      - tar xf ./release.tar
      - gzip ./release.tar
      - mv ./release.tar.gz ./$NAME-$VERSION.tar.gz
    silent: true